baseURL = ""
languageCode = "en-us"
title = "Anil Menon Website"
theme = "hugo-softe"

disqusShortname="rounddice"
paginate= 5

horizdots = "/static/img/dotsh.gif"

[params]
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
